-- Existing tables and rows are preserved. Inspect the schema before applying 0002.
CREATE TABLE IF NOT EXISTS issues (
  id TEXT PRIMARY KEY NOT NULL,
  issue_no TEXT NOT NULL DEFAULT '',
  occur_date TEXT NOT NULL DEFAULT '',
  register_date TEXT NOT NULL DEFAULT '',
  product TEXT NOT NULL DEFAULT '',
  project_no TEXT NOT NULL DEFAULT '',
  process_pnd TEXT NOT NULL DEFAULT '',
  delivery_date TEXT NOT NULL DEFAULT '',
  process TEXT NOT NULL DEFAULT '',
  issue_type TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  finder TEXT NOT NULL DEFAULT '',
  reporter TEXT NOT NULL DEFAULT '',
  reporter_id TEXT NOT NULL DEFAULT '',
  responsible_dept TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '접수',
  priority TEXT NOT NULL DEFAULT '보통',
  due_date TEXT NOT NULL DEFAULT '',
  feedback_owner TEXT NOT NULL DEFAULT '',
  cause_feedback TEXT NOT NULL DEFAULT '',
  action_detail TEXT NOT NULL DEFAULT '',
  completed_date TEXT NOT NULL DEFAULT '',
  verifier TEXT NOT NULL DEFAULT '',
  prevention TEXT NOT NULL DEFAULT '',
  followup_flag INTEGER NOT NULL DEFAULT 0,
  images TEXT NOT NULL DEFAULT '[]',
  after_images TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  history TEXT NOT NULL DEFAULT '[]',
  sample INTEGER NOT NULL DEFAULT 0
);
